apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: spinnaker
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: guestbook
        image: index.docker.io/funasakak/gcp-cd-codelab:release-1.0
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
###
---

apiVersion: v1
kind: Service
metadata:
  namespace: spinnaker
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
